### ISSUE TITLE
Effects don't appear on normal taunts anymore?

### ISSUE THREAD

**Issue by gdfsgdfg** [x07x08/TF2-Econ-Taunts#2]
Could that be an optional cvar or something.

**Comment by x07x08** [comment]
There is a cvar to toggle this behaviour : [`sm_econtaunts_defaulttaunts`](https://github.com/x07x08/TF2-Econ-Taunts/blob/65272ebd2170b6146c00aeeff507fea13ba5c77b/addons/sourcemod/scripting/TF2EconUnusualTaunts.sp#L72)
I didn't add information about any of the cvars in the readme file.
I will document them as well since it causes confusion.
